=== jgarvel076/examentema4/act 1/empresa.dtd
<!ELEMENT empresa (pedido)>
<!ELEMENT pedido (sucursal,almacen)>
<!ELEMENT sucursal (codigosucursal,nombretrabajador,fechapedido,observacionesucursal,direccion)>
<!ELEMENT codigosucursal (#PCDATA)>
<!ELEMENT nombretrabajador (#PCDATA)>
<!ELEMENT fechapedido (#PCDATA)>
<!ELEMENT observacionesucursal (urgente|incompleto)>
<!ELEMENT urgente (#PCDATA)>
<!ELEMENT incompleto (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT almacen (direccion,articulos)>
<!ELEMENT articulos (codigopedido,numerounidades,preciounidad,observacionesarticulo,plazorevision)>
<!ELEMENT codigopedido (#PCDATA)>
<!ELEMENT numerounidades (#PCDATA)>
<!ELEMENT preciounidad (#PCDATA)>
<!ELEMENT observacionesarticulo (#PCDATA)>
<!ELEMENT plazorevision (#PCDATA)>

=== jgarvel076/examentema4/act 1/empresa(validaciondtd).xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE empresa SYSTEM "empresa.dtd">
<empresa>
    <pedido>
        <sucursal>
            <codigosucursal>A1111111</codigosucursal>
            <nombretrabajador>Agustin Perez</nombretrabajador>
            <fechapedido>10/02/2023</fechapedido>
            <observacionesucursal>urgente</observacionesucursal>
            <direccion>Moreno de Mora nยบ3</direccion>
        </sucursal>
        <almacen>
            <direccion>Ubrique</direccion>
            <articulos>
                <codigopedido>AAA-111</codigopedido>
                <numerounidades>2</numerounidades>
                <preciounidad>12</preciounidad>
                <observacionesarticulo>Agarre magnetico color amarillo</observacionesarticulo>
                <plazorevision>4</plazorevision>
            </articulos>
        </almacen>
    </pedido>
</empresa>
